CREATE TABLE users (
    id VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    created TIMESTAMP(9) NOT NULL,
    modified TIMESTAMP(9) NOT NULL,
    last_login TIMESTAMP(9) NOT NULL,
    token CLOB NOT NULL,
    is_active BOOLEAN NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE phones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    number VARCHAR(255) NOT NULL,
    citycode VARCHAR(255) NOT NULL,
    contrycode VARCHAR(255) NOT NULL,
    user_id VARCHAR(255) NOT NULL,
    CONSTRAINT pk_phones PRIMARY KEY (id),
    CONSTRAINT fk_phones_user FOREIGN KEY (user_id) REFERENCES users (id)
);
